name: 'Terraform-Plan'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  terraform:
    name: 'Terraform-Plan'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        version: latest
        soft_fail: true 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    #   with:
    #     terraform_version: "1.1.7"
     
    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{secrets.TF_SA}}
        # GIT_SSH_COMMAND: "echo '${{ secrets.PRIVATE_KEY }}' > id_rsa && ssh-keyscan github.com > known_hosts && chmod 600 id_rsa known_hosts && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
    
    - name: Terraform Validate
      run: terraform validate 
      env:
        GOOGLE_CREDENTIALS: ${{secrets.TF_SA}}
    
    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{secrets.TF_SA}}